### ISSUE TITLE
about the size of the pre-extracted feature

### ISSUE THREAD

**Issue by yangwf1** [Finspire13/CMCS-Temporal-Action-Localization#4] opened 2019-09-25 11:59 UTC
hi, thanks for your sharing of the extracted features.  But i'm curious why the size of the extracted features is so large. since the validation set of THUMOS14 is about 80G, and the feature here for it is also about 80G

**Comment by Finspire13** [comment] 2019-09-26 02:24
It is because ten-crop data augmentation is used (10x file size).
And there are two type of features, i.e., I3D and UntrimmedNet.

Duplicate of #1

**Comment by yangwf1** [comment] 2019-09-26 08:43
@Finspire13 Thanks, really appreciate it. And i have one more question, is the data augmentation important or not?  Is it convenient for  you to report your result on the resized feature.

**Comment by Finspire13** [comment] 2019-09-30 01:06
@yangwf1 
Ten-crop augmentation is about 2 mAP higher than the resized feature (cant find the precise number now).
Note that the results of ablation studies in the paper are all on the ten-cropped features.

**Closed** 2019-10-04 13:33 UTC
